// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.bbdev.team/vh/pay/orders/repo"
)

// NewMockAccountsRepo creates a new instance of MockAccountsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountsRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAccountsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAccountsRepo is an autogenerated mock type for the AccountsRepo type
type MockAccountsRepo struct {
	mock.Mock
}

type MockAccountsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountsRepo) EXPECT() *MockAccountsRepo_Expecter {
	return &MockAccountsRepo_Expecter{mock: &_m.Mock}
}

// GetAccountIDByKeycloakID provides a mock function for the type MockAccountsRepo
func (_mock *MockAccountsRepo) GetAccountIDByKeycloakID(ctx context.Context, keycloakId string) (int, error) {
	ret := _mock.Called(ctx, keycloakId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountIDByKeycloakID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, keycloakId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, keycloakId)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keycloakId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountsRepo_GetAccountIDByKeycloakID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountIDByKeycloakID'
type MockAccountsRepo_GetAccountIDByKeycloakID_Call struct {
	*mock.Call
}

// GetAccountIDByKeycloakID is a helper method to define mock.On call
//   - ctx context.Context
//   - keycloakId string
func (_e *MockAccountsRepo_Expecter) GetAccountIDByKeycloakID(ctx any, keycloakId any) *MockAccountsRepo_GetAccountIDByKeycloakID_Call {
	return &MockAccountsRepo_GetAccountIDByKeycloakID_Call{Call: _e.mock.On("GetAccountIDByKeycloakID", ctx, keycloakId)}
}

func (_c *MockAccountsRepo_GetAccountIDByKeycloakID_Call) Run(run func(ctx context.Context, keycloakId string)) *MockAccountsRepo_GetAccountIDByKeycloakID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountsRepo_GetAccountIDByKeycloakID_Call) Return(n int, err error) *MockAccountsRepo_GetAccountIDByKeycloakID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountsRepo_GetAccountIDByKeycloakID_Call) RunAndReturn(run func(ctx context.Context, keycloakId string) (int, error)) *MockAccountsRepo_GetAccountIDByKeycloakID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateAccountFromProfile provides a mock function for the type MockAccountsRepo
func (_mock *MockAccountsRepo) GetOrCreateAccountFromProfile(ctx context.Context, keycloakID string) (int, error) {
	ret := _mock.Called(ctx, keycloakID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateAccountFromProfile")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, keycloakID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, keycloakID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keycloakID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountsRepo_GetOrCreateAccountFromProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateAccountFromProfile'
type MockAccountsRepo_GetOrCreateAccountFromProfile_Call struct {
	*mock.Call
}

// GetOrCreateAccountFromProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - keycloakID string
func (_e *MockAccountsRepo_Expecter) GetOrCreateAccountFromProfile(ctx any, keycloakID any) *MockAccountsRepo_GetOrCreateAccountFromProfile_Call {
	return &MockAccountsRepo_GetOrCreateAccountFromProfile_Call{Call: _e.mock.On("GetOrCreateAccountFromProfile", ctx, keycloakID)}
}

func (_c *MockAccountsRepo_GetOrCreateAccountFromProfile_Call) Run(run func(ctx context.Context, keycloakID string)) *MockAccountsRepo_GetOrCreateAccountFromProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountsRepo_GetOrCreateAccountFromProfile_Call) Return(n int, err error) *MockAccountsRepo_GetOrCreateAccountFromProfile_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountsRepo_GetOrCreateAccountFromProfile_Call) RunAndReturn(run func(ctx context.Context, keycloakID string) (int, error)) *MockAccountsRepo_GetOrCreateAccountFromProfile_Call {
	_c.Call.Return(run)
	return _c
}

// PatchOrCreateAccount provides a mock function for the type MockAccountsRepo
func (_mock *MockAccountsRepo) PatchOrCreateAccount(ctx context.Context, a repo.Account) (int, error) {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for PatchOrCreateAccount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Account) (int, error)); ok {
		return returnFunc(ctx, a)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Account) int); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.Account) error); ok {
		r1 = returnFunc(ctx, a)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountsRepo_PatchOrCreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchOrCreateAccount'
type MockAccountsRepo_PatchOrCreateAccount_Call struct {
	*mock.Call
}

// PatchOrCreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a repo.Account
func (_e *MockAccountsRepo_Expecter) PatchOrCreateAccount(ctx any, a any) *MockAccountsRepo_PatchOrCreateAccount_Call {
	return &MockAccountsRepo_PatchOrCreateAccount_Call{Call: _e.mock.On("PatchOrCreateAccount", ctx, a)}
}

func (_c *MockAccountsRepo_PatchOrCreateAccount_Call) Run(run func(ctx context.Context, a repo.Account)) *MockAccountsRepo_PatchOrCreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.Account
		if args[1] != nil {
			arg1 = args[1].(repo.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountsRepo_PatchOrCreateAccount_Call) Return(n int, err error) *MockAccountsRepo_PatchOrCreateAccount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountsRepo_PatchOrCreateAccount_Call) RunAndReturn(run func(ctx context.Context, a repo.Account) (int, error)) *MockAccountsRepo_PatchOrCreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteAccount provides a mock function for the type MockAccountsRepo
func (_mock *MockAccountsRepo) SoftDeleteAccount(ctx context.Context, accountID int) error {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountsRepo_SoftDeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteAccount'
type MockAccountsRepo_SoftDeleteAccount_Call struct {
	*mock.Call
}

// SoftDeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int
func (_e *MockAccountsRepo_Expecter) SoftDeleteAccount(ctx any, accountID any) *MockAccountsRepo_SoftDeleteAccount_Call {
	return &MockAccountsRepo_SoftDeleteAccount_Call{Call: _e.mock.On("SoftDeleteAccount", ctx, accountID)}
}

func (_c *MockAccountsRepo_SoftDeleteAccount_Call) Run(run func(ctx context.Context, accountID int)) *MockAccountsRepo_SoftDeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountsRepo_SoftDeleteAccount_Call) Return(err error) *MockAccountsRepo_SoftDeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountsRepo_SoftDeleteAccount_Call) RunAndReturn(run func(ctx context.Context, accountID int) error) *MockAccountsRepo_SoftDeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}
