// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/volatiletech/null/v9"
	"gitlab.bbdev.team/vh/pay/orders/repo"
)

// NewMockOrdersRepository creates a new instance of MockOrdersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOrdersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOrdersRepository is an autogenerated mock type for the OrdersRepository type
type MockOrdersRepository struct {
	mock.Mock
}

type MockOrdersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersRepository) EXPECT() *MockOrdersRepository_Expecter {
	return &MockOrdersRepository_Expecter{mock: &_m.Mock}
}

// ClearAllFlags provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) ClearAllFlags(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearAllFlags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_ClearAllFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllFlags'
type MockOrdersRepository_ClearAllFlags_Call struct {
	*mock.Call
}

// ClearAllFlags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) ClearAllFlags(ctx any) *MockOrdersRepository_ClearAllFlags_Call {
	return &MockOrdersRepository_ClearAllFlags_Call{Call: _e.mock.On("ClearAllFlags", ctx)}
}

func (_c *MockOrdersRepository_ClearAllFlags_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_ClearAllFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_ClearAllFlags_Call) Return(err error) *MockOrdersRepository_ClearAllFlags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_ClearAllFlags_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrdersRepository_ClearAllFlags_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) Close() {
	_mock.Called()
	return
}

// MockOrdersRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockOrdersRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockOrdersRepository_Expecter) Close() *MockOrdersRepository_Close_Call {
	return &MockOrdersRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockOrdersRepository_Close_Call) Run(run func()) *MockOrdersRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrdersRepository_Close_Call) Return() *MockOrdersRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrdersRepository_Close_Call) RunAndReturn(run func()) *MockOrdersRepository_Close_Call {
	_c.Run(run)
	return _c
}

// CreateAccount provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) CreateAccount(ctx context.Context, a repo.Account) (int, error) {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Account) (int, error)); ok {
		return returnFunc(ctx, a)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Account) int); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.Account) error); ok {
		r1 = returnFunc(ctx, a)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockOrdersRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a repo.Account
func (_e *MockOrdersRepository_Expecter) CreateAccount(ctx any, a any) *MockOrdersRepository_CreateAccount_Call {
	return &MockOrdersRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, a)}
}

func (_c *MockOrdersRepository_CreateAccount_Call) Run(run func(ctx context.Context, a repo.Account)) *MockOrdersRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.Account
		if args[1] != nil {
			arg1 = args[1].(repo.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_CreateAccount_Call) Return(n int, err error) *MockOrdersRepository_CreateAccount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrdersRepository_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, a repo.Account) (int, error)) *MockOrdersRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayment provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) CreatePayment(ctx context.Context, req repo.RequestOrder, orderID int) (*repo.Payment, error) {
	ret := _mock.Called(ctx, req, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *repo.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RequestOrder, int) (*repo.Payment, error)); ok {
		return returnFunc(ctx, req, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.RequestOrder, int) *repo.Payment); ok {
		r0 = returnFunc(ctx, req, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.RequestOrder, int) error); ok {
		r1 = returnFunc(ctx, req, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockOrdersRepository_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - req repo.RequestOrder
//   - orderID int
func (_e *MockOrdersRepository_Expecter) CreatePayment(ctx any, req any, orderID any) *MockOrdersRepository_CreatePayment_Call {
	return &MockOrdersRepository_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, req, orderID)}
}

func (_c *MockOrdersRepository_CreatePayment_Call) Run(run func(ctx context.Context, req repo.RequestOrder, orderID int)) *MockOrdersRepository_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.RequestOrder
		if args[1] != nil {
			arg1 = args[1].(repo.RequestOrder)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_CreatePayment_Call) Return(payment *repo.Payment, err error) *MockOrdersRepository_CreatePayment_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockOrdersRepository_CreatePayment_Call) RunAndReturn(run func(ctx context.Context, req repo.RequestOrder, orderID int) (*repo.Payment, error)) *MockOrdersRepository_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRenewalPayment provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) CreateRenewalPayment(ctx context.Context, data *repo.RenewalData, amount float64, currency string, pricingVersion string, pricingEvaluation null.JSON, pmx string) (*repo.Payment, error) {
	ret := _mock.Called(ctx, data, amount, currency, pricingVersion, pricingEvaluation, pmx)

	if len(ret) == 0 {
		panic("no return value specified for CreateRenewalPayment")
	}

	var r0 *repo.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repo.RenewalData, float64, string, string, null.JSON, string) (*repo.Payment, error)); ok {
		return returnFunc(ctx, data, amount, currency, pricingVersion, pricingEvaluation, pmx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repo.RenewalData, float64, string, string, null.JSON, string) *repo.Payment); ok {
		r0 = returnFunc(ctx, data, amount, currency, pricingVersion, pricingEvaluation, pmx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repo.RenewalData, float64, string, string, null.JSON, string) error); ok {
		r1 = returnFunc(ctx, data, amount, currency, pricingVersion, pricingEvaluation, pmx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_CreateRenewalPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRenewalPayment'
type MockOrdersRepository_CreateRenewalPayment_Call struct {
	*mock.Call
}

// CreateRenewalPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - data *repo.RenewalData
//   - amount float64
//   - currency string
//   - pricingVersion string
//   - pricingEvaluation null.JSON
//   - pmx string
func (_e *MockOrdersRepository_Expecter) CreateRenewalPayment(ctx any, data any, amount any, currency any, pricingVersion any, pricingEvaluation any, pmx any) *MockOrdersRepository_CreateRenewalPayment_Call {
	return &MockOrdersRepository_CreateRenewalPayment_Call{Call: _e.mock.On("CreateRenewalPayment", ctx, data, amount, currency, pricingVersion, pricingEvaluation, pmx)}
}

func (_c *MockOrdersRepository_CreateRenewalPayment_Call) Run(run func(ctx context.Context, data *repo.RenewalData, amount float64, currency string, pricingVersion string, pricingEvaluation null.JSON, pmx string)) *MockOrdersRepository_CreateRenewalPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repo.RenewalData
		if args[1] != nil {
			arg1 = args[1].(*repo.RenewalData)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 null.JSON
		if args[5] != nil {
			arg5 = args[5].(null.JSON)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_CreateRenewalPayment_Call) Return(payment *repo.Payment, err error) *MockOrdersRepository_CreateRenewalPayment_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockOrdersRepository_CreateRenewalPayment_Call) RunAndReturn(run func(ctx context.Context, data *repo.RenewalData, amount float64, currency string, pricingVersion string, pricingEvaluation null.JSON, pmx string) (*repo.Payment, error)) *MockOrdersRepository_CreateRenewalPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSpecial provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) CreateSpecial(ctx context.Context, s repo.Special) (int, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSpecial")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Special) (int, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Special) int); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.Special) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_CreateSpecial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSpecial'
type MockOrdersRepository_CreateSpecial_Call struct {
	*mock.Call
}

// CreateSpecial is a helper method to define mock.On call
//   - ctx context.Context
//   - s repo.Special
func (_e *MockOrdersRepository_Expecter) CreateSpecial(ctx any, s any) *MockOrdersRepository_CreateSpecial_Call {
	return &MockOrdersRepository_CreateSpecial_Call{Call: _e.mock.On("CreateSpecial", ctx, s)}
}

func (_c *MockOrdersRepository_CreateSpecial_Call) Run(run func(ctx context.Context, s repo.Special)) *MockOrdersRepository_CreateSpecial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.Special
		if args[1] != nil {
			arg1 = args[1].(repo.Special)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_CreateSpecial_Call) Return(n int, err error) *MockOrdersRepository_CreateSpecial_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrdersRepository_CreateSpecial_Call) RunAndReturn(run func(ctx context.Context, s repo.Special) (int, error)) *MockOrdersRepository_CreateSpecial_Call {
	_c.Call.Return(run)
	return _c
}

// CreateV2Order provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) CreateV2Order(ctx context.Context, order repo.Order) (int, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateV2Order")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Order) (int, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repo.Order) int); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repo.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_CreateV2Order_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateV2Order'
type MockOrdersRepository_CreateV2Order_Call struct {
	*mock.Call
}

// CreateV2Order is a helper method to define mock.On call
//   - ctx context.Context
//   - order repo.Order
func (_e *MockOrdersRepository_Expecter) CreateV2Order(ctx any, order any) *MockOrdersRepository_CreateV2Order_Call {
	return &MockOrdersRepository_CreateV2Order_Call{Call: _e.mock.On("CreateV2Order", ctx, order)}
}

func (_c *MockOrdersRepository_CreateV2Order_Call) Run(run func(ctx context.Context, order repo.Order)) *MockOrdersRepository_CreateV2Order_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repo.Order
		if args[1] != nil {
			arg1 = args[1].(repo.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_CreateV2Order_Call) Return(n int, err error) *MockOrdersRepository_CreateV2Order_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrdersRepository_CreateV2Order_Call) RunAndReturn(run func(ctx context.Context, order repo.Order) (int, error)) *MockOrdersRepository_CreateV2Order_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizeRenewal provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) FinalizeRenewal(ctx context.Context, orderID uint, payment *repo.Payment) error {
	ret := _mock.Called(ctx, orderID, payment)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeRenewal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *repo.Payment) error); ok {
		r0 = returnFunc(ctx, orderID, payment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_FinalizeRenewal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeRenewal'
type MockOrdersRepository_FinalizeRenewal_Call struct {
	*mock.Call
}

// FinalizeRenewal is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint
//   - payment *repo.Payment
func (_e *MockOrdersRepository_Expecter) FinalizeRenewal(ctx any, orderID any, payment any) *MockOrdersRepository_FinalizeRenewal_Call {
	return &MockOrdersRepository_FinalizeRenewal_Call{Call: _e.mock.On("FinalizeRenewal", ctx, orderID, payment)}
}

func (_c *MockOrdersRepository_FinalizeRenewal_Call) Run(run func(ctx context.Context, orderID uint, payment *repo.Payment)) *MockOrdersRepository_FinalizeRenewal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *repo.Payment
		if args[2] != nil {
			arg2 = args[2].(*repo.Payment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_FinalizeRenewal_Call) Return(err error) *MockOrdersRepository_FinalizeRenewal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_FinalizeRenewal_Call) RunAndReturn(run func(ctx context.Context, orderID uint, payment *repo.Payment) error) *MockOrdersRepository_FinalizeRenewal_Call {
	_c.Call.Return(run)
	return _c
}

// FlagOrder provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) FlagOrder(ctx context.Context, id int, flag string) error {
	ret := _mock.Called(ctx, id, flag)

	if len(ret) == 0 {
		panic("no return value specified for FlagOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, flag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_FlagOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlagOrder'
type MockOrdersRepository_FlagOrder_Call struct {
	*mock.Call
}

// FlagOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - flag string
func (_e *MockOrdersRepository_Expecter) FlagOrder(ctx any, id any, flag any) *MockOrdersRepository_FlagOrder_Call {
	return &MockOrdersRepository_FlagOrder_Call{Call: _e.mock.On("FlagOrder", ctx, id, flag)}
}

func (_c *MockOrdersRepository_FlagOrder_Call) Run(run func(ctx context.Context, id int, flag string)) *MockOrdersRepository_FlagOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_FlagOrder_Call) Return(err error) *MockOrdersRepository_FlagOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_FlagOrder_Call) RunAndReturn(run func(ctx context.Context, id int, flag string) error) *MockOrdersRepository_FlagOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FlagOrdersToRenew provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) FlagOrdersToRenew(ctx context.Context, month int64, year int64) (int64, error) {
	ret := _mock.Called(ctx, month, year)

	if len(ret) == 0 {
		panic("no return value specified for FlagOrdersToRenew")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return returnFunc(ctx, month, year)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = returnFunc(ctx, month, year)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, month, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_FlagOrdersToRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlagOrdersToRenew'
type MockOrdersRepository_FlagOrdersToRenew_Call struct {
	*mock.Call
}

// FlagOrdersToRenew is a helper method to define mock.On call
//   - ctx context.Context
//   - month int64
//   - year int64
func (_e *MockOrdersRepository_Expecter) FlagOrdersToRenew(ctx any, month any, year any) *MockOrdersRepository_FlagOrdersToRenew_Call {
	return &MockOrdersRepository_FlagOrdersToRenew_Call{Call: _e.mock.On("FlagOrdersToRenew", ctx, month, year)}
}

func (_c *MockOrdersRepository_FlagOrdersToRenew_Call) Run(run func(ctx context.Context, month int64, year int64)) *MockOrdersRepository_FlagOrdersToRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_FlagOrdersToRenew_Call) Return(n int64, err error) *MockOrdersRepository_FlagOrdersToRenew_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrdersRepository_FlagOrdersToRenew_Call) RunAndReturn(run func(ctx context.Context, month int64, year int64) (int64, error)) *MockOrdersRepository_FlagOrdersToRenew_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetAccount(ctx context.Context, id int, email string) (*repo.Account, error) {
	ret := _mock.Called(ctx, id, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *repo.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (*repo.Account, error)); ok {
		return returnFunc(ctx, id, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) *repo.Account); ok {
		r0 = returnFunc(ctx, id, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, id, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockOrdersRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - email string
func (_e *MockOrdersRepository_Expecter) GetAccount(ctx any, id any, email any) *MockOrdersRepository_GetAccount_Call {
	return &MockOrdersRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id, email)}
}

func (_c *MockOrdersRepository_GetAccount_Call) Run(run func(ctx context.Context, id int, email string)) *MockOrdersRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetAccount_Call) Return(account *repo.Account, err error) *MockOrdersRepository_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockOrdersRepository_GetAccount_Call) RunAndReturn(run func(ctx context.Context, id int, email string) (*repo.Account, error)) *MockOrdersRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSpecialsByEmail provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetAllSpecialsByEmail(ctx context.Context, email string) ([]*repo.Special, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSpecialsByEmail")
	}

	var r0 []*repo.Special
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*repo.Special, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*repo.Special); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repo.Special)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetAllSpecialsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSpecialsByEmail'
type MockOrdersRepository_GetAllSpecialsByEmail_Call struct {
	*mock.Call
}

// GetAllSpecialsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockOrdersRepository_Expecter) GetAllSpecialsByEmail(ctx any, email any) *MockOrdersRepository_GetAllSpecialsByEmail_Call {
	return &MockOrdersRepository_GetAllSpecialsByEmail_Call{Call: _e.mock.On("GetAllSpecialsByEmail", ctx, email)}
}

func (_c *MockOrdersRepository_GetAllSpecialsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockOrdersRepository_GetAllSpecialsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetAllSpecialsByEmail_Call) Return(specials []*repo.Special, err error) *MockOrdersRepository_GetAllSpecialsByEmail_Call {
	_c.Call.Return(specials, err)
	return _c
}

func (_c *MockOrdersRepository_GetAllSpecialsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) ([]*repo.Special, error)) *MockOrdersRepository_GetAllSpecialsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlaggedOrders provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetFlaggedOrders(ctx context.Context) ([]repo.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFlaggedOrders")
	}

	var r0 []repo.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repo.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repo.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetFlaggedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlaggedOrders'
type MockOrdersRepository_GetFlaggedOrders_Call struct {
	*mock.Call
}

// GetFlaggedOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) GetFlaggedOrders(ctx any) *MockOrdersRepository_GetFlaggedOrders_Call {
	return &MockOrdersRepository_GetFlaggedOrders_Call{Call: _e.mock.On("GetFlaggedOrders", ctx)}
}

func (_c *MockOrdersRepository_GetFlaggedOrders_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_GetFlaggedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetFlaggedOrders_Call) Return(orders []repo.Order, err error) *MockOrdersRepository_GetFlaggedOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrdersRepository_GetFlaggedOrders_Call) RunAndReturn(run func(ctx context.Context) ([]repo.Order, error)) *MockOrdersRepository_GetFlaggedOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfflinePayments provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetOfflinePayments(ctx context.Context, skip int, limit int, method string, orderByCreatedAt string) ([]*repo.OfflinePayment, error) {
	ret := _mock.Called(ctx, skip, limit, method, orderByCreatedAt)

	if len(ret) == 0 {
		panic("no return value specified for GetOfflinePayments")
	}

	var r0 []*repo.OfflinePayment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]*repo.OfflinePayment, error)); ok {
		return returnFunc(ctx, skip, limit, method, orderByCreatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*repo.OfflinePayment); ok {
		r0 = returnFunc(ctx, skip, limit, method, orderByCreatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repo.OfflinePayment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
		r1 = returnFunc(ctx, skip, limit, method, orderByCreatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetOfflinePayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfflinePayments'
type MockOrdersRepository_GetOfflinePayments_Call struct {
	*mock.Call
}

// GetOfflinePayments is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - limit int
//   - method string
//   - orderByCreatedAt string
func (_e *MockOrdersRepository_Expecter) GetOfflinePayments(ctx any, skip any, limit any, method any, orderByCreatedAt any) *MockOrdersRepository_GetOfflinePayments_Call {
	return &MockOrdersRepository_GetOfflinePayments_Call{Call: _e.mock.On("GetOfflinePayments", ctx, skip, limit, method, orderByCreatedAt)}
}

func (_c *MockOrdersRepository_GetOfflinePayments_Call) Run(run func(ctx context.Context, skip int, limit int, method string, orderByCreatedAt string)) *MockOrdersRepository_GetOfflinePayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetOfflinePayments_Call) Return(offlinePayments []*repo.OfflinePayment, err error) *MockOrdersRepository_GetOfflinePayments_Call {
	_c.Call.Return(offlinePayments, err)
	return _c
}

func (_c *MockOrdersRepository_GetOfflinePayments_Call) RunAndReturn(run func(ctx context.Context, skip int, limit int, method string, orderByCreatedAt string) ([]*repo.OfflinePayment, error)) *MockOrdersRepository_GetOfflinePayments_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderIDsToRenew provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetOrderIDsToRenew(ctx context.Context) ([]uint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderIDsToRenew")
	}

	var r0 []uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]uint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []uint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetOrderIDsToRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderIDsToRenew'
type MockOrdersRepository_GetOrderIDsToRenew_Call struct {
	*mock.Call
}

// GetOrderIDsToRenew is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) GetOrderIDsToRenew(ctx any) *MockOrdersRepository_GetOrderIDsToRenew_Call {
	return &MockOrdersRepository_GetOrderIDsToRenew_Call{Call: _e.mock.On("GetOrderIDsToRenew", ctx)}
}

func (_c *MockOrdersRepository_GetOrderIDsToRenew_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_GetOrderIDsToRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetOrderIDsToRenew_Call) Return(uints []uint, err error) *MockOrdersRepository_GetOrderIDsToRenew_Call {
	_c.Call.Return(uints, err)
	return _c
}

func (_c *MockOrdersRepository_GetOrderIDsToRenew_Call) RunAndReturn(run func(ctx context.Context) ([]uint, error)) *MockOrdersRepository_GetOrderIDsToRenew_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderIDsWithPricingError provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetOrderIDsWithPricingError(ctx context.Context) ([]uint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderIDsWithPricingError")
	}

	var r0 []uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]uint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []uint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetOrderIDsWithPricingError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderIDsWithPricingError'
type MockOrdersRepository_GetOrderIDsWithPricingError_Call struct {
	*mock.Call
}

// GetOrderIDsWithPricingError is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) GetOrderIDsWithPricingError(ctx any) *MockOrdersRepository_GetOrderIDsWithPricingError_Call {
	return &MockOrdersRepository_GetOrderIDsWithPricingError_Call{Call: _e.mock.On("GetOrderIDsWithPricingError", ctx)}
}

func (_c *MockOrdersRepository_GetOrderIDsWithPricingError_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_GetOrderIDsWithPricingError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetOrderIDsWithPricingError_Call) Return(uints []uint, err error) *MockOrdersRepository_GetOrderIDsWithPricingError_Call {
	_c.Call.Return(uints, err)
	return _c
}

func (_c *MockOrdersRepository_GetOrderIDsWithPricingError_Call) RunAndReturn(run func(ctx context.Context) ([]uint, error)) *MockOrdersRepository_GetOrderIDsWithPricingError_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersToSkipDouble provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetOrdersToSkipDouble(ctx context.Context, year int, month int, lastDay time.Time) ([]string, error) {
	ret := _mock.Called(ctx, year, month, lastDay)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersToSkipDouble")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, time.Time) ([]string, error)); ok {
		return returnFunc(ctx, year, month, lastDay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, time.Time) []string); ok {
		r0 = returnFunc(ctx, year, month, lastDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, time.Time) error); ok {
		r1 = returnFunc(ctx, year, month, lastDay)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetOrdersToSkipDouble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersToSkipDouble'
type MockOrdersRepository_GetOrdersToSkipDouble_Call struct {
	*mock.Call
}

// GetOrdersToSkipDouble is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - month int
//   - lastDay time.Time
func (_e *MockOrdersRepository_Expecter) GetOrdersToSkipDouble(ctx any, year any, month any, lastDay any) *MockOrdersRepository_GetOrdersToSkipDouble_Call {
	return &MockOrdersRepository_GetOrdersToSkipDouble_Call{Call: _e.mock.On("GetOrdersToSkipDouble", ctx, year, month, lastDay)}
}

func (_c *MockOrdersRepository_GetOrdersToSkipDouble_Call) Run(run func(ctx context.Context, year int, month int, lastDay time.Time)) *MockOrdersRepository_GetOrdersToSkipDouble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetOrdersToSkipDouble_Call) Return(strings []string, err error) *MockOrdersRepository_GetOrdersToSkipDouble_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOrdersRepository_GetOrdersToSkipDouble_Call) RunAndReturn(run func(ctx context.Context, year int, month int, lastDay time.Time) ([]string, error)) *MockOrdersRepository_GetOrdersToSkipDouble_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersToSkipFresh provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetOrdersToSkipFresh(ctx context.Context, year int, month int, lastDay time.Time) ([]string, error) {
	ret := _mock.Called(ctx, year, month, lastDay)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersToSkipFresh")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, time.Time) ([]string, error)); ok {
		return returnFunc(ctx, year, month, lastDay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, time.Time) []string); ok {
		r0 = returnFunc(ctx, year, month, lastDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, time.Time) error); ok {
		r1 = returnFunc(ctx, year, month, lastDay)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetOrdersToSkipFresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersToSkipFresh'
type MockOrdersRepository_GetOrdersToSkipFresh_Call struct {
	*mock.Call
}

// GetOrdersToSkipFresh is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - month int
//   - lastDay time.Time
func (_e *MockOrdersRepository_Expecter) GetOrdersToSkipFresh(ctx any, year any, month any, lastDay any) *MockOrdersRepository_GetOrdersToSkipFresh_Call {
	return &MockOrdersRepository_GetOrdersToSkipFresh_Call{Call: _e.mock.On("GetOrdersToSkipFresh", ctx, year, month, lastDay)}
}

func (_c *MockOrdersRepository_GetOrdersToSkipFresh_Call) Run(run func(ctx context.Context, year int, month int, lastDay time.Time)) *MockOrdersRepository_GetOrdersToSkipFresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetOrdersToSkipFresh_Call) Return(strings []string, err error) *MockOrdersRepository_GetOrdersToSkipFresh_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOrdersRepository_GetOrdersToSkipFresh_Call) RunAndReturn(run func(ctx context.Context, year int, month int, lastDay time.Time) ([]string, error)) *MockOrdersRepository_GetOrdersToSkipFresh_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentByID provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetPaymentByID(ctx context.Context, id int) (*repo.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 *repo.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repo.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repo.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetPaymentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentByID'
type MockOrdersRepository_GetPaymentByID_Call struct {
	*mock.Call
}

// GetPaymentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrdersRepository_Expecter) GetPaymentByID(ctx any, id any) *MockOrdersRepository_GetPaymentByID_Call {
	return &MockOrdersRepository_GetPaymentByID_Call{Call: _e.mock.On("GetPaymentByID", ctx, id)}
}

func (_c *MockOrdersRepository_GetPaymentByID_Call) Run(run func(ctx context.Context, id int)) *MockOrdersRepository_GetPaymentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetPaymentByID_Call) Return(payment *repo.Payment, err error) *MockOrdersRepository_GetPaymentByID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockOrdersRepository_GetPaymentByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*repo.Payment, error)) *MockOrdersRepository_GetPaymentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokensForOrders provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetTokensForOrders(ctx context.Context, orderIDs []int) (map[int]string, error) {
	ret := _mock.Called(ctx, orderIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetTokensForOrders")
	}

	var r0 map[int]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) (map[int]string, error)); ok {
		return returnFunc(ctx, orderIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) map[int]string); ok {
		r0 = returnFunc(ctx, orderIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, orderIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetTokensForOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokensForOrders'
type MockOrdersRepository_GetTokensForOrders_Call struct {
	*mock.Call
}

// GetTokensForOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - orderIDs []int
func (_e *MockOrdersRepository_Expecter) GetTokensForOrders(ctx any, orderIDs any) *MockOrdersRepository_GetTokensForOrders_Call {
	return &MockOrdersRepository_GetTokensForOrders_Call{Call: _e.mock.On("GetTokensForOrders", ctx, orderIDs)}
}

func (_c *MockOrdersRepository_GetTokensForOrders_Call) Run(run func(ctx context.Context, orderIDs []int)) *MockOrdersRepository_GetTokensForOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetTokensForOrders_Call) Return(intToString map[int]string, err error) *MockOrdersRepository_GetTokensForOrders_Call {
	_c.Call.Return(intToString, err)
	return _c
}

func (_c *MockOrdersRepository_GetTokensForOrders_Call) RunAndReturn(run func(ctx context.Context, orderIDs []int) (map[int]string, error)) *MockOrdersRepository_GetTokensForOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUniqueEmailsFromSpecial provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) GetUniqueEmailsFromSpecial(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueEmailsFromSpecial")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_GetUniqueEmailsFromSpecial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUniqueEmailsFromSpecial'
type MockOrdersRepository_GetUniqueEmailsFromSpecial_Call struct {
	*mock.Call
}

// GetUniqueEmailsFromSpecial is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) GetUniqueEmailsFromSpecial(ctx any) *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call {
	return &MockOrdersRepository_GetUniqueEmailsFromSpecial_Call{Call: _e.mock.On("GetUniqueEmailsFromSpecial", ctx)}
}

func (_c *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call) Return(strings []string, err error) *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockOrdersRepository_GetUniqueEmailsFromSpecial_Call {
	_c.Call.Return(run)
	return _c
}

// LoadRenewalData provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) LoadRenewalData(ctx context.Context, orderID uint) (*repo.RenewalData, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for LoadRenewalData")
	}

	var r0 *repo.RenewalData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*repo.RenewalData, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *repo.RenewalData); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.RenewalData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_LoadRenewalData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRenewalData'
type MockOrdersRepository_LoadRenewalData_Call struct {
	*mock.Call
}

// LoadRenewalData is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint
func (_e *MockOrdersRepository_Expecter) LoadRenewalData(ctx any, orderID any) *MockOrdersRepository_LoadRenewalData_Call {
	return &MockOrdersRepository_LoadRenewalData_Call{Call: _e.mock.On("LoadRenewalData", ctx, orderID)}
}

func (_c *MockOrdersRepository_LoadRenewalData_Call) Run(run func(ctx context.Context, orderID uint)) *MockOrdersRepository_LoadRenewalData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_LoadRenewalData_Call) Return(renewalData *repo.RenewalData, err error) *MockOrdersRepository_LoadRenewalData_Call {
	_c.Call.Return(renewalData, err)
	return _c
}

func (_c *MockOrdersRepository_LoadRenewalData_Call) RunAndReturn(run func(ctx context.Context, orderID uint) (*repo.RenewalData, error)) *MockOrdersRepository_LoadRenewalData_Call {
	_c.Call.Return(run)
	return _c
}

// MarkResolvedForRenew provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) MarkResolvedForRenew(ctx context.Context, orderIDs []uint) error {
	ret := _mock.Called(ctx, orderIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkResolvedForRenew")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = returnFunc(ctx, orderIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_MarkResolvedForRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkResolvedForRenew'
type MockOrdersRepository_MarkResolvedForRenew_Call struct {
	*mock.Call
}

// MarkResolvedForRenew is a helper method to define mock.On call
//   - ctx context.Context
//   - orderIDs []uint
func (_e *MockOrdersRepository_Expecter) MarkResolvedForRenew(ctx any, orderIDs any) *MockOrdersRepository_MarkResolvedForRenew_Call {
	return &MockOrdersRepository_MarkResolvedForRenew_Call{Call: _e.mock.On("MarkResolvedForRenew", ctx, orderIDs)}
}

func (_c *MockOrdersRepository_MarkResolvedForRenew_Call) Run(run func(ctx context.Context, orderIDs []uint)) *MockOrdersRepository_MarkResolvedForRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint
		if args[1] != nil {
			arg1 = args[1].([]uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_MarkResolvedForRenew_Call) Return(err error) *MockOrdersRepository_MarkResolvedForRenew_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_MarkResolvedForRenew_Call) RunAndReturn(run func(ctx context.Context, orderIDs []uint) error) *MockOrdersRepository_MarkResolvedForRenew_Call {
	_c.Call.Return(run)
	return _c
}

// SkipOrdersByUserKey provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) SkipOrdersByUserKey(ctx context.Context, userkey string) (int, error) {
	ret := _mock.Called(ctx, userkey)

	if len(ret) == 0 {
		panic("no return value specified for SkipOrdersByUserKey")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userkey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userkey)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userkey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_SkipOrdersByUserKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkipOrdersByUserKey'
type MockOrdersRepository_SkipOrdersByUserKey_Call struct {
	*mock.Call
}

// SkipOrdersByUserKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userkey string
func (_e *MockOrdersRepository_Expecter) SkipOrdersByUserKey(ctx any, userkey any) *MockOrdersRepository_SkipOrdersByUserKey_Call {
	return &MockOrdersRepository_SkipOrdersByUserKey_Call{Call: _e.mock.On("SkipOrdersByUserKey", ctx, userkey)}
}

func (_c *MockOrdersRepository_SkipOrdersByUserKey_Call) Run(run func(ctx context.Context, userkey string)) *MockOrdersRepository_SkipOrdersByUserKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_SkipOrdersByUserKey_Call) Return(n int, err error) *MockOrdersRepository_SkipOrdersByUserKey_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrdersRepository_SkipOrdersByUserKey_Call) RunAndReturn(run func(ctx context.Context, userkey string) (int, error)) *MockOrdersRepository_SkipOrdersByUserKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrdersUserKeyFromAccounts provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) UpdateOrdersUserKeyFromAccounts(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrdersUserKeyFromAccounts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrdersUserKeyFromAccounts'
type MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call struct {
	*mock.Call
}

// UpdateOrdersUserKeyFromAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrdersRepository_Expecter) UpdateOrdersUserKeyFromAccounts(ctx any) *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call {
	return &MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call{Call: _e.mock.On("UpdateOrdersUserKeyFromAccounts", ctx)}
}

func (_c *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call) Run(run func(ctx context.Context)) *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call) Return(err error) *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrdersRepository_UpdateOrdersUserKeyFromAccounts_Call {
	_c.Call.Return(run)
	return _c
}
