BEGIN;

ALTER TABLE payments_offline
ALTER COLUMN deleted_at SET DEFAULT TIMESTAMP WITH TIME ZONE DEFAULT now();

ALTER TABLE payments_helphaver
ALTER COLUMN deleted_at SET DEFAULT TIMESTAMP WITH TIME ZONE DEFAULT now();

COMMIT;