stages:
  - build
  - deploy

variables:
  STAGING_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  STAGING_LATEST_IMAGE: $CI_REGISTRY_IMAGE:staging
  PROD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  PROD_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
build_staging:
  image: docker:latest
  stage: build
  tags:
    - staging
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $STAGING_LATEST_IMAGE
    - docker build --cache-from $STAGING_LATEST_IMAGE -t $STAGING_IMAGE .
    - docker tag $STAGING_IMAGE $STAGING_LATEST_IMAGE
    - docker push $STAGING_IMAGE
    - docker push $STAGING_LATEST_IMAGE
  only:
    - master

deploy_staging:
  variables:
    # we want to use the db in staging server itself.
    DB_HOST: "ordersdb" #"${DEV_PG_HOST}"
    DB_PORT: ${DEV_PG_PORT}
    DB_USER: ${DEV_ORDER_PG_USER}
    DB_DATABASE: ${DEV_ORDER_PG_DBNAME}
    DB_PASSWORD: ${DEV_PG_PWD}
    S3_SECRET_KEY: ${S3_SECRET_KEY}
    S3_ACCESS_KEY: ${S3_ACCESS_KEY}
    S3_REGION: ${S3_REGION}
    S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    S3_ENDPOINT: ${S3_ENDPOINT}
    PELECARD_USER: ${PELECARD_USER}
    PELECARD_PASSWORD: ${PELECARD_PASSWORD}
    SUFX: ${DEV_SUFX}
    KEYCLOAK_SERVER_URL: ${DYN_STAGING_KEYCLOAK_SERVER_BASE_URL}
    KEYCLOAK_REALM: ${DYN_STAGING_KEYCLOAK_REALM}
    KEYCLOAK_CLIENT_ID: ${DYN_STAGING_KEYCLOAK_CONFIDENTIAL_CLIENT_ID}
    KEYCLOAK_CLIENT_SECRET: ${DYN_STAGING_KEYCLOAK_CONFIDENTIAL_CLIENT_SECRET}
    PROFILE_SERVICE_URL: ${DYN_STAGING_PROFILE_SERVICE_URL}
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.7.0
  stage: deploy
  tags:
    - staging
  script:
    - env
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - IMAGE_NAME=$STAGING_IMAGE docker-compose up -d ordersdb
    - sleep 60
    - IMAGE_NAME=$STAGING_IMAGE docker-compose up -d vh-srv-orders
  only:
    - master


build_production:
  image: docker:latest
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $PROD_IMAGE .
    - docker push $PROD_IMAGE
  only:
    - tags

deploy_production:
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.7.0
  stage: deploy
  tags:
    - production
  variables:
    DB_HOST: ${PROD_PG_HOST}
    DB_PORT: ${PROD_PG_PORT}
    DB_USER: ${PROD_ORDER_PG_USER}
    DB_DATABASE: ${PROD_ORDER_PG_DBNAME}
    DB_PASSWORD: ${PROD_PG_PWD}
    SUFX: ${PROD_SUFX}
    KEYCLOAK_SERVER_URL: ${DYN_PROD_KEYCLOAK_SERVER_BASE_URL}
    KEYCLOAK_REALM: ${DYN_PROD_KEYCLOAK_REALM}
    KEYCLOAK_CLIENT_ID: ${DYN_PROD_KEYCLOAK_CONFIDENTIAL_CLIENT_ID}
    KEYCLOAK_CLIENT_SECRET: ${DYN_PROD_KEYCLOAK_CONFIDENTIAL_CLIENT_SECRET}
    PROFILE_SERVICE_URL: ${DYN_PROD_PROFILE_SERVICE_URL}
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - IMAGE_NAME=$PROD_IMAGE docker-compose up -d vh-srv-orders
  only:
    - tags
  when: manual

