version: '2'
services:
  ordersdb:
    container_name: 'ordersdb'
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  vh-srv-orders:
    container_name: 'vh-srv-orders'
    image: "${IMAGE_NAME}"
    restart: unless-stopped
    environment:
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      PGDATABASE: ${DB_DATABASE}
      PORT: ":8185"
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      PELECARD_USER: ${PELECARD_USER}
      PELECARD_PASSWORD: ${PELECARD_PASSWORD}
      SUFX: "${DEV_SUFX}"
    mem_limit: 250M
    ports:
      - 8185:8185
networks:
  default:
    external:
      name: vh
