version: '2'
services:
  stagingdb:
    image: postgres:latest
    container_name: orderdb
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - ${PGPORT}:5432
