version: '2'
services:
  ordersdb:
    container_name: 'ordersdb'
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nats:
    container_name: 'nats'
    image: nats:2.10
    restart: unless-stopped
    volumes:
      - nats_data:/storage
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--store_dir", "/storage", "--user", "${NATS_USER}", "--pass", "${NATS_PASSWORD}", "--http_port", "8222"]
  vh-srv-orders:
    container_name: 'vh-srv-orders'
    image: "${IMAGE_NAME}"
    restart: unless-stopped
    volumes:
      - /root/google_application_credentials.json:/vh_google_app_creds.json:ro
    environment:
      PORT: ":8185"
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      PGDATABASE: ${DB_DATABASE}
      NATS_URL: ${NATS_URL}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      PELECARD_USER: ${PELECARD_USER}
      PELECARD_PASSWORD: ${PELECARD_PASSWORD}
      SUFX: "${DEV_SUFX}"
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      PROFILE_SERVICE_URL: ${PROFILE_SERVICE_URL}
      GOOGLE_APPLICATION_CREDENTIALS: /vh_google_app_creds.json
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    mem_limit: 250M
    ports:
      - "8185:8185"
networks:
  default:
    external:
      name: vh
volumes:
  nats_data: