package domain

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/getsentry/sentry-go"
	"github.com/jackc/pgx/v4"
	"github.com/volatiletech/null/v9"

	"gitlab.bbdev.team/vh/pay/orders/common"
	"gitlab.bbdev.team/vh/pay/orders/events"
	"gitlab.bbdev.team/vh/pay/orders/pkg/keycloak"
	"gitlab.bbdev.team/vh/pay/orders/pkg/profiles"
	"gitlab.bbdev.team/vh/pay/orders/pkg/utils"
	"gitlab.bbdev.team/vh/pay/orders/repo"
)

var interestingEvents = map[string]struct{}{
	profiles.TypeCreateProfile:     {},
	profiles.TypeUpdateProfile:     {},
	profiles.TypeDeleteProfile:     {},
	profiles.TypeHardDeleteProfile: {},
	// profiles.TypeMergeAccounts:     {},
}

var errSkip = errors.New("skip event")

type EventsHandler struct {
	repo           repo.OrdersRepository
	kcTokenSource  keycloak.TokenSource
	profileService profiles.ProfileService
}

func NewEventsHandler(repo repo.OrdersRepository) *EventsHandler {
	eh := new(EventsHandler)
	eh.repo = repo
	eh.kcTokenSource = keycloak.NewClient()
	eh.profileService = profiles.NewProfileServiceAPI(eh.kcTokenSource)
	return eh
}

func (eh *EventsHandler) HandleProfilesEvent(event profiles.Event) {
	ctx := eh.newContext(event)

	if eh.shouldSkip(event) {
		return
	}

	err := errSkip

	switch event.Type {
	case profiles.TypeCreateProfile:
		err = eh.onCreateProfile(ctx, event)
	case profiles.TypeUpdateProfile:
		err = eh.onUpdateProfile(ctx, event)
	case profiles.TypeDeleteProfile:
		err = eh.onDeleteProfile(ctx, event)
	case profiles.TypeHardDeleteProfile:
		err = eh.onHardDeleteProfile(ctx, event)
	default:
	}

	if err != nil && !errors.Is(err, errSkip) {
		utils.LogFor(ctx).Error("domain.EventsHandler.HandleProfilesEvent",
			slog.String("event_type", event.Type), slog.Any("err", err))
		sentry.CaptureException(err)
	}
}

func (eh *EventsHandler) BuildEvent(eventType string, payload map[string]interface{}) events.Event {
	event := events.MakeEvent(eventType, payload)
	event.Component = events.ComponentProfileEventHandler
	event.Actor = events.ActorSystem
	return event
}

func (eh *EventsHandler) SetProfileService(ps profiles.ProfileService) {
	eh.profileService = ps
}

func (eh *EventsHandler) newContext(event profiles.Event) context.Context {
	logger := slog.Default().With(slog.String("nats_nuid", event.ID))
	ctx := context.WithValue(context.Background(), common.CtxLogger, logger)
	ctx = context.WithValue(ctx, common.CtxTokenSource, eh.kcTokenSource)
	ctx = context.WithValue(ctx, common.CtxEventBuilder, eh)

	hub := sentry.CurrentHub().Clone()
	hub.ConfigureScope(func(scope *sentry.Scope) {
		scope.SetTag("nats_nuid", event.ID)
	})
	ctx = sentry.SetHubOnContext(ctx, hub)

	return ctx
}

func (eh *EventsHandler) shouldSkip(event profiles.Event) bool {
	// skip events with no direct impact on accounts
	if _, ok := interestingEvents[event.Type]; !ok {
		return true
	}

	// skip events generated by our cron jobs
	if event.Component == profiles.ComponentAPI && event.Actor == common.ServiceName {
		return true
	}

	return false
}

func (eh *EventsHandler) onCreateProfile(ctx context.Context, event profiles.Event) error {
	keycloakID, ok := event.Payload["keycloak_id"]
	if !ok {
		return errors.New("no keycloak_id in event payload")
	}

	utils.LogFor(ctx).Info("Create profile event", slog.String("keycloak_id", keycloakID.(string)))

	_, err := eh.repo.GetOrCreateAccountFromProfile(ctx, keycloakID.(string))
	if err != nil {
		return fmt.Errorf("eh.repo.GetOrCreateAccount: %w", err)
	}

	return nil
}

func (eh *EventsHandler) onUpdateProfile(ctx context.Context, event profiles.Event) error {
	keycloakID, ok := event.Payload["keycloak_id"]
	if !ok {
		return errors.New("no keycloak_id in event payload")
	}

	utils.LogFor(ctx).Info("Update profile event", slog.String("keycloak_id", keycloakID.(string)))

	profile, err := eh.profileService.GetProfileByKeycloakID(ctx, keycloakID.(string))
	if err != nil {
		if errors.Is(err, profiles.ErrNotFound) {
			return fmt.Errorf("eh.profileService.GetProfileByKeycloakID: profile not found")
		}
		return fmt.Errorf("eh.profileService.GetProfileByKeycloakID: %w", err)
	}

	account := repo.Account{
		UserKey:     null.StringFrom(profile.KeycloakID.String()),
		Email:       null.StringFromPtr(profile.PrimaryEmail),
		FirstName:   null.StringFromPtr(profile.FirstNameVernacular),
		LastName:    null.StringFromPtr(profile.LastNameVernacular),
		Country:     null.StringFromPtr(profile.Country),
		City:        null.StringFromPtr(profile.City),
		State:       null.StringFromPtr(profile.StateOrRegion),
		Street:      null.StringFromPtr(profile.StreetAddress),
		Postcode:    null.StringFromPtr(profile.PostalCode),
		Phone:       null.StringFromPtr(profile.MobileNumber),
		AccountType: null.NewString("personal", true),
	}

	_, err = eh.repo.PatchOrCreateAccount(ctx, account)
	if err != nil {
		return fmt.Errorf("eh.repo.PatchOrCreateAccount: %w", err)
	}

	return nil
}

func (eh *EventsHandler) onDeleteProfile(ctx context.Context, event profiles.Event) error {
	keycloakID, ok := event.Payload["keycloak_id"]
	if !ok {
		return errors.New("no keycloak_id in event payload")
	}

	utils.LogFor(ctx).Info("Delete profile event", slog.String("keycloak_id", keycloakID.(string)))

	accountID, err := eh.repo.GetAccountIDByKeycloakID(ctx, keycloakID.(string))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			utils.LogFor(ctx).Info("onDeleteProfile: account not found, nothing to delete",
				slog.String("keycloak_id", keycloakID.(string)))
			return nil
		}
		return fmt.Errorf("eh.repo.GetAccountIDByKeycloakID: %w", err)
	}

	err = eh.repo.SoftDeleteAccount(ctx, accountID)
	if err != nil {
		return fmt.Errorf("eh.repo.SoftDeleteAccount: %w", err)
	}

	return nil
}

func (eh *EventsHandler) onHardDeleteProfile(ctx context.Context, event profiles.Event) error {
	return nil
}
