// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.bbdev.team/vh/pay/orders/pkg/accounting"
)

// NewMockAccountingService creates a new instance of MockAccountingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountingService {
	mock := &MockAccountingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountingService is an autogenerated mock type for the AccountingService type
type MockAccountingService struct {
	mock.Mock
}

type MockAccountingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountingService) EXPECT() *MockAccountingService_Expecter {
	return &MockAccountingService_Expecter{mock: &_m.Mock}
}

// GetEuropeContributions provides a mock function for the type MockAccountingService
func (_mock *MockAccountingService) GetEuropeContributions(ctx context.Context, emails []string) (*accounting.EuropeContributionsResult, error) {
	ret := _mock.Called(ctx, emails)

	if len(ret) == 0 {
		panic("no return value specified for GetEuropeContributions")
	}

	var r0 *accounting.EuropeContributionsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (*accounting.EuropeContributionsResult, error)); ok {
		return returnFunc(ctx, emails)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) *accounting.EuropeContributionsResult); ok {
		r0 = returnFunc(ctx, emails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accounting.EuropeContributionsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, emails)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountingService_GetEuropeContributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEuropeContributions'
type MockAccountingService_GetEuropeContributions_Call struct {
	*mock.Call
}

// GetEuropeContributions is a helper method to define mock.On call
//   - ctx context.Context
//   - emails []string
func (_e *MockAccountingService_Expecter) GetEuropeContributions(ctx interface{}, emails interface{}) *MockAccountingService_GetEuropeContributions_Call {
	return &MockAccountingService_GetEuropeContributions_Call{Call: _e.mock.On("GetEuropeContributions", ctx, emails)}
}

func (_c *MockAccountingService_GetEuropeContributions_Call) Run(run func(ctx context.Context, emails []string)) *MockAccountingService_GetEuropeContributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountingService_GetEuropeContributions_Call) Return(europeContributionsResult *accounting.EuropeContributionsResult, err error) *MockAccountingService_GetEuropeContributions_Call {
	_c.Call.Return(europeContributionsResult, err)
	return _c
}

func (_c *MockAccountingService_GetEuropeContributions_Call) RunAndReturn(run func(ctx context.Context, emails []string) (*accounting.EuropeContributionsResult, error)) *MockAccountingService_GetEuropeContributions_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastContributions provides a mock function for the type MockAccountingService
func (_mock *MockAccountingService) GetLastContributions(ctx context.Context, email string, companyID *string) (*accounting.ContributionsResult, error) {
	ret := _mock.Called(ctx, email, companyID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastContributions")
	}

	var r0 *accounting.ContributionsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (*accounting.ContributionsResult, error)); ok {
		return returnFunc(ctx, email, companyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) *accounting.ContributionsResult); ok {
		r0 = returnFunc(ctx, email, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accounting.ContributionsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, email, companyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountingService_GetLastContributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastContributions'
type MockAccountingService_GetLastContributions_Call struct {
	*mock.Call
}

// GetLastContributions is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - companyID *string
func (_e *MockAccountingService_Expecter) GetLastContributions(ctx interface{}, email interface{}, companyID interface{}) *MockAccountingService_GetLastContributions_Call {
	return &MockAccountingService_GetLastContributions_Call{Call: _e.mock.On("GetLastContributions", ctx, email, companyID)}
}

func (_c *MockAccountingService_GetLastContributions_Call) Run(run func(ctx context.Context, email string, companyID *string)) *MockAccountingService_GetLastContributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountingService_GetLastContributions_Call) Return(contributionsResult *accounting.ContributionsResult, err error) *MockAccountingService_GetLastContributions_Call {
	_c.Call.Return(contributionsResult, err)
	return _c
}

func (_c *MockAccountingService_GetLastContributions_Call) RunAndReturn(run func(ctx context.Context, email string, companyID *string) (*accounting.ContributionsResult, error)) *MockAccountingService_GetLastContributions_Call {
	_c.Call.Return(run)
	return _c
}
