// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.bbdev.team/vh/pay/orders/pkg/profiles"
)

// NewMockProfileService creates a new instance of MockProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileService {
	mock := &MockProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileService is an autogenerated mock type for the ProfileService type
type MockProfileService struct {
	mock.Mock
}

type MockProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileService) EXPECT() *MockProfileService_Expecter {
	return &MockProfileService_Expecter{mock: &_m.Mock}
}

// GetProfileByKeycloakID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetProfileByKeycloakID(ctx context.Context, keycloakId string) (*profiles.Profile, error) {
	ret := _mock.Called(ctx, keycloakId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByKeycloakID")
	}

	var r0 *profiles.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*profiles.Profile, error)); ok {
		return returnFunc(ctx, keycloakId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *profiles.Profile); ok {
		r0 = returnFunc(ctx, keycloakId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profiles.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keycloakId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetProfileByKeycloakID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileByKeycloakID'
type MockProfileService_GetProfileByKeycloakID_Call struct {
	*mock.Call
}

// GetProfileByKeycloakID is a helper method to define mock.On call
//   - ctx context.Context
//   - keycloakId string
func (_e *MockProfileService_Expecter) GetProfileByKeycloakID(ctx interface{}, keycloakId interface{}) *MockProfileService_GetProfileByKeycloakID_Call {
	return &MockProfileService_GetProfileByKeycloakID_Call{Call: _e.mock.On("GetProfileByKeycloakID", ctx, keycloakId)}
}

func (_c *MockProfileService_GetProfileByKeycloakID_Call) Run(run func(ctx context.Context, keycloakId string)) *MockProfileService_GetProfileByKeycloakID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetProfileByKeycloakID_Call) Return(profile *profiles.Profile, err error) *MockProfileService_GetProfileByKeycloakID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileService_GetProfileByKeycloakID_Call) RunAndReturn(run func(ctx context.Context, keycloakId string) (*profiles.Profile, error)) *MockProfileService_GetProfileByKeycloakID_Call {
	_c.Call.Return(run)
	return _c
}

// LookupProfile provides a mock function for the type MockProfileService
func (_mock *MockProfileService) LookupProfile(ctx context.Context, email string) (*profiles.Profile, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for LookupProfile")
	}

	var r0 *profiles.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*profiles.Profile, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *profiles.Profile); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profiles.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_LookupProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupProfile'
type MockProfileService_LookupProfile_Call struct {
	*mock.Call
}

// LookupProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockProfileService_Expecter) LookupProfile(ctx interface{}, email interface{}) *MockProfileService_LookupProfile_Call {
	return &MockProfileService_LookupProfile_Call{Call: _e.mock.On("LookupProfile", ctx, email)}
}

func (_c *MockProfileService_LookupProfile_Call) Run(run func(ctx context.Context, email string)) *MockProfileService_LookupProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_LookupProfile_Call) Return(profile *profiles.Profile, err error) *MockProfileService_LookupProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileService_LookupProfile_Call) RunAndReturn(run func(ctx context.Context, email string) (*profiles.Profile, error)) *MockProfileService_LookupProfile_Call {
	_c.Call.Return(run)
	return _c
}

// LookupProfileByKeycloakId provides a mock function for the type MockProfileService
func (_mock *MockProfileService) LookupProfileByKeycloakId(ctx context.Context, keycloakId string) (*profiles.Profile, error) {
	ret := _mock.Called(ctx, keycloakId)

	if len(ret) == 0 {
		panic("no return value specified for LookupProfileByKeycloakId")
	}

	var r0 *profiles.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*profiles.Profile, error)); ok {
		return returnFunc(ctx, keycloakId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *profiles.Profile); ok {
		r0 = returnFunc(ctx, keycloakId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profiles.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keycloakId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_LookupProfileByKeycloakId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupProfileByKeycloakId'
type MockProfileService_LookupProfileByKeycloakId_Call struct {
	*mock.Call
}

// LookupProfileByKeycloakId is a helper method to define mock.On call
//   - ctx context.Context
//   - keycloakId string
func (_e *MockProfileService_Expecter) LookupProfileByKeycloakId(ctx interface{}, keycloakId interface{}) *MockProfileService_LookupProfileByKeycloakId_Call {
	return &MockProfileService_LookupProfileByKeycloakId_Call{Call: _e.mock.On("LookupProfileByKeycloakId", ctx, keycloakId)}
}

func (_c *MockProfileService_LookupProfileByKeycloakId_Call) Run(run func(ctx context.Context, keycloakId string)) *MockProfileService_LookupProfileByKeycloakId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_LookupProfileByKeycloakId_Call) Return(profile *profiles.Profile, err error) *MockProfileService_LookupProfileByKeycloakId_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileService_LookupProfileByKeycloakId_Call) RunAndReturn(run func(ctx context.Context, keycloakId string) (*profiles.Profile, error)) *MockProfileService_LookupProfileByKeycloakId_Call {
	_c.Call.Return(run)
	return _c
}
